// Code generated by gormgen. DO NOT EDIT.
package model

import (
	"gorm.io/gorm"
)

const (
	UserTableName = "user"

	userFieldId         = "id"
	userFieldNickname   = "nickname"
	userFieldUsername   = "username"
	userFieldPassword   = "password"
	userFieldSalt       = "salt"
	userFieldPhone      = "phone"
	userFieldStatus     = "status"
	userFieldCreateTime = "create_time"
	userFieldUpdateTime = "update_time"
	userFieldDeleted    = "deleted"
)

// Holds all SQL columns for user fields.
var userFieldAll = []string{
	userFieldId,
	userFieldNickname,
	userFieldUsername,
	userFieldPassword,
	userFieldSalt,
	userFieldPhone,
	userFieldStatus,
	userFieldCreateTime,
	userFieldUpdateTime,
	userFieldDeleted,
}

// Kernel struct for table operation
type UserOption struct {
	selects []string
	orders  []string
	wheres  []struct {
		prefix string
		values []interface{}
	}
	page *struct {
		pageNum  int
		pageSize int
	}
}

func NewUserOption() *UserOption {
	return &UserOption{}
}

func (opt *UserOption) BuildQuery(db *gorm.DB) *gorm.DB {
	if opt.selects != nil {
		db = db.Select(opt.selects)
	}
	for _, v := range opt.orders {
		db = db.Order(v)
	}
	for _, q := range opt.wheres {
		db = db.Where(q.prefix, q.values...)
	}
	return db
}

func (opt *UserOption) BuildPage(db *gorm.DB) *gorm.DB {
	if p := opt.page; p != nil {
		if p.pageNum <= 0 {
			p.pageNum = 1
		}
		db = db.Limit(p.pageSize).Offset((p.pageNum - 1) * p.pageSize)
	}
	return db
}

func (opt *UserOption) Select(fields ...string) *UserOption {
	opt.selects = fields
	return opt
}

func (opt *UserOption) SelectAll() *UserOption {
	opt.selects = userFieldAll
	return opt
}

func (opt *UserOption) GetSelect() []string {
	return opt.selects
}

func (opt *UserOption) OrderBy(value string) *UserOption {
	opt.orders = append(opt.orders, value)
	return opt
}

func (opt *UserOption) Where(query string, args ...interface{}) *UserOption {
	opt.wheres = append(opt.wheres, struct {
		prefix string
		values []interface{}
	}{
		query,
		args,
	})
	return opt
}

func (opt *UserOption) SetPage(pageNum, pageSize int) *UserOption {
	opt.page = &struct {
		pageNum  int
		pageSize int
	}{
		pageNum,
		pageSize,
	}
	return opt
}
