package tpl

const (
	ModelHeader = `// Code generated by gormgen. DO NOT EDIT.
package %s

import (
	"time"
)
`
)

var (
	ModelTemplate = `
var {{.StructName.UpperS}}TableName = "{{.TableName}}"

// {{.StructName.UpperS}} table model
type {{.StructName.UpperS}} struct { {{range $item := .Columns}}
	{{$item.FieldName}}	{{$item.FieldType}}	` + "`" + `gorm:"column:{{$item.GormName}}{{$item.PrimaryKey}}" json:"{{$item.JsonName}}"` + "`" + ` // {{$item.Comment}} {{end}}
}

func ({{.StructName.LowerS}} *{{.StructName.UpperS}}) TableName() string {
	return {{.StructName.UpperS}}TableName
}

`
)
